// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6JktCkZgRHhvBGLCfiRKDsix2mKwIuY',
    appId: '1:504061241739:android:0d61bb74c0d2206241678e',
    messagingSenderId: '504061241739',
    projectId: 'g44-moviles-new',
    storageBucket: 'g44-moviles-new.firebasestorage.app',
  );


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZiW36bBtJTOtswcpiQr9Nu_NrHyFPjc',
    appId: '1:504061241739:web:ba0dafae4125c5d541678e',
    messagingSenderId: '504061241739',
    projectId: 'g44-moviles-new',
    authDomain: 'g44-moviles-new.firebaseapp.com',
    storageBucket: 'g44-moviles-new.firebasestorage.app',
    measurementId: 'G-WSS4P6GS4P',
  );

}