// rutas centrales para navegación
const String routeReport        = '/report';
const String routeReportsList   = '/reports-list';
const String routeProtocols     = '/protocols';
const String routeTraining      = '/training';
const String routeNotifications = '/notification';
const String routeProfile       = '/profile';
const String routeDashboard     = '/dashboard';
const String routeRegister      = '/register';
const String routeLogin         = '/login';
